server:
  port: 8040

spring:
  data:
    mongodb:
      uri: mongodb://usr:pwd@localhost:27017/hw11?authSource=admin

mongock:
  enabled: false
  migration-scan-package:
    - ru.otus.hw.migrations
 