spring:
  data:
    mongodb:
      uri: mongodb://myuser2:mypassword2@localhost:27018/admin?authSource=admin

mongock:
  enabled: true
  migration-scan-package:
    - ru.otus.hw.migrations

logging:
  level:
    io:
      mongock: DEBUG
