CREATE TABLE IF NOT EXISTS acl_sid (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  principal BOOLEAN NOT NULL,
  sid VARCHAR(100) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_acl_sid UNIQUE (sid, principal)
);

CREATE TABLE IF NOT EXISTS acl_class (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  class VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_acl_class UNIQUE (class)
);

CREATE TABLE IF NOT EXISTS acl_object_identity (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  object_id_class BIGINT NOT NULL,
  object_id_identity BIGINT NOT NULL,
  parent_object BIGINT,
  owner_sid BIGINT,
  entries_inheriting BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_acl_object_identity UNIQUE (object_id_class, object_id_identity)
);

CREATE TABLE IF NOT EXISTS acl_entry (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  acl_object_identity BIGINT NOT NULL,
  ace_order INTEGER NOT NULL,
  sid BIGINT NOT NULL,
  mask INTEGER NOT NULL,
  granting BOOLEAN NOT NULL,
  audit_success BOOLEAN NOT NULL,
  audit_failure BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_acl_entry UNIQUE (acl_object_identity, ace_order)
);

ALTER TABLE acl_entry ADD FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity(id);
ALTER TABLE acl_entry ADD FOREIGN KEY (sid) REFERENCES acl_sid(id);
ALTER TABLE acl_object_identity ADD FOREIGN KEY (parent_object) REFERENCES acl_object_identity(id);
ALTER TABLE acl_object_identity ADD FOREIGN KEY (object_id_class) REFERENCES acl_class(id);
ALTER TABLE acl_object_identity ADD FOREIGN KEY (owner_sid) REFERENCES acl_sid(id);